In [1]:
import sys
!{sys.executable} -m pip install sklearn


In [2]:
import sklearn
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
knn = KNeighborsRegressor(n_neighbors=3)

ModuleNotFoundError: No module named 'sklearn'

In [ ]:

#function that numericalizes the strings and converts them into lists with 27 elements so all x's are the same size
def numericalize(word):
    #key for numericalizing letters
    letkey = ["","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    #creates an empty list of size 27
    replacement = [0]*27
    #for every letter in the alphabet, if the letter is in the word, change the index of that spot of the replacement to the number assigned to the letter in the key
    for key in letkey:
        if key in word:
            replacement[letkey.index(key)] = letkey.index(key)
        else:
            replacement[letkey.index(key)] = 0
    #old code
    """for let in word:
        replacement.append(letkey.index(let))"""

    return replacement

with open("completed.txt") as dataset:
    lines = dataset.readlines()
xtrain = []
data = []
#split the data to fomrat it
for line in lines:
    data.append(line.split("-"))
#xtrain is everything but the last 3 ytrain is the opposite
xtrain = [x[:-3] for x in data] 
ytrain = [x[-3:] for x in data]
#the first index is the guess number, which cannot be numericalized as its not in the key, so we just turn it into a list of size 27 with only one index being the guess number and everything else empty
for x in range(len(xtrain)):
    xtrain[x][0] = [int(xtrain[x][0])]+[0]*26

#goes through all the indexes of xtrain
for x in range(len(xtrain)):
    #goes through every piece of data
    for y in range(12):
        #checks if the data is None and turns it into a list of 27 Nones
        if xtrain[x][y] == 'None':
            xtrain[x][y] = [0]*27
        #checks if its a str and numericalizes it
        if type(xtrain[x][y]) == str:
            xtrain[x][y] = numericalize(xtrain[x][y])
        """if y != 0:
            print(xtrain[x][y])
            xtrain[x][0] += xtrain[x][y]
        xtrain[x] = xtrain[x][0]"""
#runs through the y's and numericalizes it
for x in range(len(ytrain)):
        ytrain[x][0] = numericalize(ytrain[x][0])   
        ytrain[x][2] = ytrain[x][2].replace("\n","")
        ytrain[x][0] += [ytrain[x][1]]
        ytrain[x][0] += [ytrain[x][2]]
        ytrain[x] = ytrain[x][0]




In [ ]:
x = [[[1],[2],[3]],[[4],[5],[6]]]
npx = np.array(x)
print(npx)
print(npx.shape)
npx = npx.reshape(2,3)
print(npx)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)
[[1 2 3]
 [4 5 6]]


In [ ]:
#print(xtrain[3])
npxtrain = np.array(xtrain)
#print(npxtrain.shape)
npxtrain = npxtrain.reshape(208,324)
print(len(npxtrain))
print(npxtrain.shape)
print(npxtrain[5])

208
(208, 324)
[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  0  0  0  5  0  0  0  9  0  0  0  0  0  0  0  0 18  0 20
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0
  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0

In [ ]:
print(len(ytrain))
a = 0
for x in range(len(ytrain)):
    try:
        print(ytrain[x][0][0])
    except:
        a+=1
print(a)
print(ytrain[0])
npytrain = np.array(ytrain)
print(npytrain.shape)

208
208
[0, 1, None, None, None, 5, None, None, None, 9, None, None, None, None, None, None, None, None, 18, None, 20, None, None, None, None, None, None, '12398', '0']
(208, 29)


In [ ]:
import warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
print(len(xtrain),len(ytrain))
print(npxtrain.shape)
knn.fit(npxtrain,npytrain)

208 208
(208, 324)


KNeighborsRegressor(n_neighbors=3)

In [ ]:
print(npxtrain[5])
print(npxtrain[5].shape)
"""testvalue = npxtrain[5]
testvalue = list(testvalue.reshape(1,-1))
print(testvalue)
knn.predict(testvalue)"""
a = 0
for ele in npxtrain:
    try:
        knn.predict(list(ele.reshape(1,-1)))
    except:
        a+=1
print(a)

[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  0  0  0  5  0  0  0  9  0  0  0  0  0  0  0  0 18  0 20
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0
  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0]
(324,)
208
