In [9]:
import sys
!{sys.executable} -m pip install sklearn



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import sklearn
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
knn = KNeighborsRegressor(n_neighbors=3)

In [11]:

#function that numericalizes the strings and converts them into lists with 27 elements so all x's are the same size
def numericalize(word):
    #key for numericalizing letters
    letkey = ["","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    #creates an empty list of size 27
    replacement = [0]*27
    #for every letter in the alphabet, if the letter is in the word, change the index of that spot of the replacement to the number assigned to the letter in the key
    for key in letkey:
        if key in word:
            replacement[letkey.index(key)] = letkey.index(key)
        else:
            replacement[letkey.index(key)] = 0
    #old code
    """for let in word:
        replacement.append(letkey.index(let))"""

    return replacement

with open("completed.txt") as dataset:
    lines = dataset.readlines()
xtrain = []
data = []
#split the data to fomrat it
for line in lines:
    data.append(line.split("-"))
#xtrain is everything but the last 3 ytrain is the opposite
xtrain = [x[:-3] for x in data] 
ytrain = [x[-3:] for x in data]
#the first index is the guess number, which cannot be numericalized as its not in the key, so we just turn it into a list of size 27 with only one index being the guess number and everything else empty
for x in range(len(xtrain)):
    xtrain[x][0] = [int(xtrain[x][0])]+[0]*26

#goes through all the indexes of xtrain
for x in range(len(xtrain)):
    #goes through every piece of data
    for y in range(12):
        #checks if the data is None and turns it into a list of 27 Nones
        if xtrain[x][y] == 'None':
            xtrain[x][y] = [0]*27
        #checks if its a str and numericalizes it
        if type(xtrain[x][y]) == str:
            xtrain[x][y] = numericalize(xtrain[x][y])
        """if y != 0:
            print(xtrain[x][y])
            xtrain[x][0] += xtrain[x][y]
        xtrain[x] = xtrain[x][0]"""
#runs through the y's and numericalizes it
for x in range(len(ytrain)):
        ytrain[x][0] = numericalize(ytrain[x][0])   
        ytrain[x][2] = ytrain[x][2].replace("\n","")
        ytrain[x][0] += [ytrain[x][1]]
        ytrain[x][0] += [ytrain[x][2]]
        ytrain[x] = ytrain[x][0]




In [12]:
#test for how reshaping np arrays works
x = [[[1],[2],[3]],[[4],[5],[6]]]
npx = np.array(x)
print(npx)
print(npx.shape)
npx = npx.reshape(2,3)
print(npx)
print(type(npx[0][0]))
print(np.mean(npx))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)
[[1 2 3]
 [4 5 6]]
<class 'numpy.int32'>
3.5


In [13]:
#print(xtrain[3])
#turns xtrain into a np array
npxtrain = np.array(xtrain)
#print(npxtrain.shape)
#reshapes it into a 2d array of 208 indexes with 324 indexes
npxtrain = npxtrain.reshape(208,324)
print(len(npxtrain))
print(npxtrain.shape)
print(npxtrain[5])

208
(208, 324)
[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  0  0  0  5  0  0  0  9  0  0  0  0  0  0  0  0 18  0 20
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0
  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0

In [14]:
print(len(ytrain))
a = 0
#test to make sure that y train is 2d
for x in range(len(ytrain)):
    try:
        print(ytrain[x][0][0])
    except:
        a+=1

print(a)
print(ytrain[0])
#turns ytrain into a nparray
npytrain = np.array(ytrain)
print(npytrain.shape)

208
208
[0, 1, 0, 0, 0, 5, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 18, 0, 20, 0, 0, 0, 0, 0, 0, '12398', '0']
(208, 29)


In [15]:
print(len(xtrain),len(ytrain))
print(npxtrain.shape)
npytrain = npytrain.astype(float)
#fits the ml model
fxtrain = npxtrain.astype(float)
knn.fit(fxtrain,npytrain)

208 208
(208, 324)


KNeighborsRegressor(n_neighbors=3)

In [16]:
data = np.array(['1', '2', '3', '4', '7', '9', '10', '12'])
datanew = data.astype(int)
#attempt to calculate median of values
np.mean(datanew)
#https://www.statology.org/typeerror-cannot-perform-reduce-with-flexible-type/

6.0

In [17]:

print(type(npxtrain[207][10]))

print(type(fxtrain[207][10]))
for x in range(len(npxtrain)):
  for y in range(324):
    fxtrain[x][y] = int(npxtrain[x][y])
p = 0
for x in range(len(fxtrain)):
  for y in range(324):
    if np.issubdtype(fxtrain[x][y].dtype, float) != True:
      p+=1
print(p,"non-float data points in fxtrain")
print(npxtrain[5].shape)
#old code
"""testvalue = npxtrain[5]
testvalue = list(testvalue.reshape(1,-1))
print(testvalue)
knn.predict(testvalue)"""
a = 0
#tries to predict the outcome of every single piece of data in the dataset, which all of them throw errors
"""for ele in fxtrain:
    try:
        knn.predict(list(ele.reshape(1,-1)))
    except:
        a+=1"""
print(a, "failed predictions in fxtrain")
print(type(npxtrain))
fxtrain = npxtrain.astype(float)
"""for ele in fxtrain[0]:
  print(type(ele))"""
print(fxtrain[0])
preds = knn.predict(fxtrain[0].reshape(1,-1))

<class 'numpy.int32'>
<class 'numpy.float64'>
0 non-float data points in fxtrain
(324,)
0 failed predictions in fxtrain
<class 'numpy.ndarray'>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [18]:
def format_predictions(predictions, intent):
    formatted_predictions = []
    for x in range(len(predictions)):
        if intent == "fresh":
            formatted_predictions.append(list(predictions[x][:26]))
        if intent == "list":
            
            formatted_predictions.append([predictions[x][27]])
    return formatted_predictions
fresh_prediction = format_predictions(preds, "fresh")
list_prediction = format_predictions(preds,"list")
print(fresh_prediction)
print(list_prediction)

[[0.0, 1.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 9.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 18.0, 0.0, 20.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
[[12398.0]]


In [19]:
def denumericalize(predictions):
    letkey = ["","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    word = ""
    wordlist = []
    for x in range(len(predictions)):
        for y in range(len(predictions[x])):
            word+=letkey[int(predictions[x][y])]
        wordlist.append(word)
    return wordlist
predicted_words = denumericalize(fresh_prediction)
print(predicted_words)

['aeirt']


In [20]:
def search_word(listpreds):
    finallist = []
    with open("possibleguesses.txt") as pguesses:
        lines = pguesses.readlines()
    for x in range(len(listpreds)):
        finallist.append(lines[int(listpreds[x][0])-1])
    for x in range(len(finallist)):
        finallist[x] = finallist[x].replace("\n","")
    return(finallist)
searched_predictions = search_word(list_prediction)
print(searched_predictions)

['iotas']


In [21]:
from colorama import init
init()
import random
from turtle import pos
import time
#colored text
from termcolor import colored
#opens the list of possible wordle words
with open("incomplete.txt","r") as f:
    lines = f.readlines()

#picks a random word and cleans it up
line = random.randint(0,len(lines))
#print (line)
word = lines[line]
word = word[:5]
p = open("possibleguesses.txt","r")
possibleguesses = p.readlines()
for ind in range(len(possibleguesses)):
    possibleguesses[ind] = possibleguesses[ind].replace("\n","")

In [26]:
guessed = False
#picks a random word and cleans it up
line = random.randint(0,len(lines))
#print (line)
word = lines[line]
word = word[:5]
guess = input()
word = word.lower()
print(word)
guessnumber = 0
#A string of all guessed letters
guessedletters = ""
previousguesses = []
#stores the colors for each letter to be printed
greenletters = [None,None,None,None,None]
yellowletters = [None,None,None,None,None]
while guessed != True:
    letcolors = [None,None,None,None,None]
    if guess == word.lower():
        print("yay")
        letcolors = ["green" for x in letcolors]
        complete = True
        break
    else:
        #goes through each letter of the guess and sees if its a match, if the letter is in the word, or its neither
        for place in range(5):
            #checks for a letter match
            if guess[place] == word[place]:
                #stores the matched letter to the corresponding place in greenletters
                greenletters[place] = word[place]
                #says that that letters color should be green when printed
                letcolors[place] = "green"
            #checks if letter is in the word
            elif guess[place] in word:
                #stores the matched letter to the corresponding place in green letters:
                if yellowletters[place] != None and guess[place] not in yellowletters[place]:
                    yellowletters[place] += guess[place]
                else:
                    yellowletters[place] = guess[place]
                #says that that letters color should be yellow when printed
                letcolors[place] = "yellow"
            else:
                #says that that letter's color should be gray when printed
                letcolors[place] = "white"
        #prints each of the previous guesses and their colors
    for g in previousguesses:
        print(colored(g[0][0],g[1][0]),colored(g[0][1],g[1][1]),colored(g[0][2],g[1][2]),colored(g[0][3],g[1][3]),colored(g[0][4],g[1][4]))
    
    #prints the current guess and its colors
    print(colored(guess[0],letcolors[0]),colored(guess[1],letcolors[1]),colored(guess[2],letcolors[2]),colored(guess[3],letcolors[3]),colored(guess[4],letcolors[4]))
    previousguesses.append([guess,letcolors])
    #adds newly guessed letters to the total guessed letters
    for let in guess:
        if let not in guessedletters:
            guessedletters+=let
    guessnumber+=1
        